spring：
    profiles:
        active:
        - dev
---
spring：
    profiles: dev
    application:
        name:asdasdadsdsda
---
spring：
    profiles: test
    application:
        name:asdasdadsdsda